fint:
  kafka:
    application-id: fagprove-elev-status
    enable-ssl: false
    default-replicas: 1
    topic:
      org-id: fintlabs-no
      domain-context: fagprove

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fagprove-elev-status